const money = value => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const icon = id => `<svg aria-hidden="true"><use href="assets/icons.svg#${id}"/></svg>`;
const slug = new URLSearchParams(location.search).get("produto");
fetch("data/products.json").then(response => { if (!response.ok) throw new Error(); return response.json(); }).then(products => {
  const product = products.find(item => item.slug === slug);
  if (!product) throw new Error();
  document.title = `${product.name} | PequenosABC`;
  document.querySelector('meta[name="description"]').content = product.description;
  document.querySelector("#product").innerHTML = `<nav class="breadcrumb" aria-label="Navegação estrutural"><a href="index.html">Materiais</a><span aria-hidden="true">›</span><span>${product.name}</span></nav><section class="product-detail"><div class="detail-cover" style="--cover:${product.color}">${product.badge ? `<span class="badge">${product.badge}</span>` : ""}<span class="cover-art">${icon("book")}</span><span>Material pedagógico digital</span><h1>${product.name}</h1><small>Arquivo em PDF</small></div><div class="detail-copy"><span class="kicker">Material digital</span><h1>${product.name}</h1><p>${product.description}</p><div class="price">${product.oldPrice ? `<del>${money(product.oldPrice)}</del>` : ""}<strong>${money(product.price)}</strong><small>Pagamento único</small></div><button class="buy" type="button" data-add-cart="${product.slug}">${icon("cart")} Adicionar ao carrinho</button><p class="safe">${icon("shield")} Compra segura e entrega por e-mail após a confirmação.</p></div></section><section class="product-content"><article><h2>O que você vai receber</h2><p>${product.short}</p><ul>${product.contents.map(item => `<li>${icon("check")} ${item}</li>`).join("")}</ul></article><aside><h3>Sobre o material</h3><p>${icon("file")}<span><small>Formato</small><b>PDF digital</b></span></p><p>${icon("download")}<span><small>Entrega</small><b>Por e-mail</b></span></p><p>${icon("shield")}<span><small>Acesso</small><b>Link privado</b></span></p></aside></section>`;
}).catch(() => { document.querySelector("#product").innerHTML = `<div class="empty product-error"><h1>Material não encontrado</h1><p>Este endereço pode estar incorreto ou o material não está mais disponível.</p><a class="primary" href="index.html">Voltar à loja</a></div>`; });
